### ISSUE TITLE
Add ability to set the initial rep date

### ISSUE THREAD

**Issue by bjsi** [bjsi/incremental-writing#25]

**Comment by bjsi** [comment]
Depend on nldates?

**Comment by pjeby** [comment]
While on this subject, it may be useful to use a "next date" column instead of a "last date".  This would simplify identifying due dates (and the work done during sorting) since the interval calculation would then be done only when scheduling an item.  In addition, it would make it easier to manually reschedule something using the table, or to sort the table by review date for viewing purposes.  (E.g. using the [Advanced Tables](https://github.com/tgrosinger/advanced-tables-obsidian) plugin.)

Also, using a next date means you could "snooze" an item to some future date, which isn't possible using the interval system.  (Granted, such snoozing probably means your priority is set wrong, but still...)

**Comment by bjsi** [comment]
I agree with all of those points. What I am planning to do is:

- Add a YAML metadata block at the top of the queue file where you can specify scheduling info.
- Remove the A Factor column for each row and have a per-queue A-Factor in the YAML metadata part.
- Keep the interval column.
- Change the last rep date column to a next rep date column.

**Comment by bjsi** [comment]
done!
